{
  "hash": "417f4cc5c70399eae787e019f0d24c0e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ex19. Causal Inference: Mixed Backends with GPD - Amoroso Kernel\"\n---\n\n\n\n\n> **Legacy vignette (for the website / historical notes).**\n> These files may not match the current exported API one-to-one.\n> Last verified: **2026-01-18**.\n>\n> For the up-to-date workflow, see the main package vignettes (basic, unconditional, conditional, and causal)..\n\n\n# Causal Inference: Mixed Backends with GPD - Amoroso Kernel {#causal-different-backends-gpd}\n\nThis vignette fits two mixed-backend causal models with GPD tails and an Amoroso kernel:\n\n- Model A: Treated = SB, Control = CRP\n- Model B: Treated = CRP, Control = SB\n\nWe shift y to keep outcomes in a stable positive range.\n\n---\n\n## Data Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"causal_alt_real500_p4_k2\", package = \"DPmixGPD\")\ny_raw <- causal_alt_real500_p4_k2$y\nT <- causal_alt_real500_p4_k2$T\nX <- as.matrix(causal_alt_real500_p4_k2$X)\n\nshift <- abs(min(y_raw)) + 0.1\ny <- y_raw + shift\n\nsummary_tbl <- tibble(\n  statistic = c(\"N\", \"Mean\", \"SD\", \"Min\", \"Max\"),\n  value = c(length(y), mean(y), sd(y), min(y), max(y))\n)\n\nsummary_tbl %>%\n  mutate(value = signif(value, 4)) %>%\n  kable(caption = \"Shifted Outcome Summary (Amoroso)\", align = \"c\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE, position = \"center\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Shifted Outcome Summary (Amoroso)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> statistic </th>\n   <th style=\"text-align:center;\"> value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> N </td>\n   <td style=\"text-align:center;\"> 500.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Mean </td>\n   <td style=\"text-align:center;\"> 8.46 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> SD </td>\n   <td style=\"text-align:center;\"> 1.76 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Min </td>\n   <td style=\"text-align:center;\"> 0.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Max </td>\n   <td style=\"text-align:center;\"> 13.46 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\nx_eval <- X[1:40, , drop = FALSE]\ny_eval <- y[1:40]\nu_threshold <- as.numeric(stats::quantile(y, 0.8, names = FALSE))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_causal <- data.frame(y = y, T = as.factor(T), x1 = X[, 1])\n\np_scatter <- ggplot(df_causal, aes(x = x1, y = y, color = T)) +\n  geom_point(alpha = 0.5) +\n  labs(title = \"Shifted Outcome vs X1\", x = \"X1\", y = \"y (shifted)\", color = \"Treatment\") +\n  theme_minimal()\n\np_scatter\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/data-scatter-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Model A: Treated SB, Control CRP (Amoroso + GPD)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparam_specs_gpd <- list(\n  gpd = list(\n    threshold = list(\n      mode = \"dist\",\n      dist = \"lognormal\",\n      # Use max() to guard against log(0) = -Inf by enforcing a positive lower bound.\n      args = list(meanlog = log(max(u_threshold, .Machine$double.eps)), sdlog = 0.25)\n    )\n  )\n)\n\nbundle_sb_crp <- build_causal_bundle(\n  y = y,\n  T = T,\n  X = X,\n  kernel = c(\"amoroso\", \"amoroso\"),\n  backend = c(\"sb\", \"crp\"),\n  PS = \"logit\",\n  GPD = c(TRUE, TRUE),\n  components = c(5, 5),\n  param_specs = param_specs_gpd,\n  mcmc_outcome = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 1),\n  mcmc_ps = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 1)\n)\n\nbundle_sb_crp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDPmixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n   <td style=\"text-align:center;\"> Chinese Restaurant Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> amoroso </td>\n   <td style=\"text-align:center;\"> amoroso </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bundle_sb_crp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDPmixGPD causal bundle summary\nDPmixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n   <td style=\"text-align:center;\"> Chinese Restaurant Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> amoroso </td>\n   <td style=\"text-align:center;\"> amoroso </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_sb_crp <- run_mcmc_causal(bundle_sb_crp)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: beta\n===== Samplers =====\nRW sampler (5)\n  - beta[]  (5 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|-------------|-------------|-------------|-------------|\n|-------------------------------------------------------|\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] Registering 'dAmorosoGpd' as a distribution based on its use in BUGS code. If you make changes to the nimbleFunctions for the distribution, you must call 'deregisterDistributions' before using the distribution in BUGS code for those changes to take effect.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] 'ps' is provided in 'data' but is not a variable in the model and is being ignored.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_tail_scale, loc, scale, shape1, shape2, tail_shape, threshold, z\n===== Samplers =====\nRW sampler (6)\n  - threshold\n  - beta_tail_scale[]  (4 elements)\n  - tail_shape\nCRP_concentration sampler (1)\n  - alpha\nCRP_cluster_wrapper sampler (20)\n  - loc[]  (5 elements)\n  - scale[]  (5 elements)\n  - shape1[]  (5 elements)\n  - shape2[]  (5 elements)\nCRP sampler (1)\n  - z[1:232] \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] sampler_CRP: The number of clusters based on the cluster parameters\n            is less than the number of potential clusters. The MCMC is not\n            strictly valid if it ever proposes more components than cluster\n            parameters exist; NIMBLE will warn you if this occurs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] To calculate WAIC, set 'WAIC = TRUE', in addition to having enabled WAIC in building the MCMC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [Warning] CRP_sampler: This MCMC is not for a proper model. The MCMC attempted to use more components than the number of cluster parameters. Please increase the number of cluster parameters.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating WAIC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_loc, beta_ps_loc, beta_ps_scale, beta_scale, beta_tail_scale, shape1, shape2, tail_shape, threshold, w, z\n===== Samplers =====\nRW sampler (71)\n  - alpha\n  - shape1[]  (5 elements)\n  - shape2[]  (5 elements)\n  - beta_loc[]  (20 elements)\n  - beta_ps_loc[]  (5 elements)\n  - beta_scale[]  (20 elements)\n  - beta_ps_scale[]  (5 elements)\n  - threshold\n  - beta_tail_scale[]  (4 elements)\n  - tail_shape\n  - v[]  (4 elements)\ncategorical sampler (268)\n  - z[]  (268 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] To calculate WAIC, set 'WAIC = TRUE', in addition to having enabled WAIC in building the MCMC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating WAIC.\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_sb_crp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-- PS fit --\nDPmixGPD PS fit\nmodel: logit \n\n-- Outcome fits --\n[control]\nMixGPD fit | backend: Chinese Restaurant Process | kernel: Amoroso Distribution | GPD tail: TRUE\nn = 232 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n\n[treated]\nMixGPD fit | backend: Stick-Breaking Process | kernel: Amoroso Distribution | GPD tail: TRUE\nn = 268 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n```\n\n\n:::\n\n```{.r .cell-code}\nparams(fit_sb_crp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPosterior mean parameters (causal)\n\n[treated]\nPosterior mean parameters\n\n$alpha\n[1] \"0.53\"\n\n$w\n[1] \"0.995\"\n\n$beta_loc\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> 0.061 </td>\n   <td style=\"text-align:center;\"> -1.243 </td>\n   <td style=\"text-align:center;\"> -0.182 </td>\n   <td style=\"text-align:center;\"> 0.235 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> 0.214 </td>\n   <td style=\"text-align:center;\"> 0.472 </td>\n   <td style=\"text-align:center;\"> -1.306 </td>\n   <td style=\"text-align:center;\"> 0.836 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> 0.147 </td>\n   <td style=\"text-align:center;\"> -0.25 </td>\n   <td style=\"text-align:center;\"> 0.124 </td>\n   <td style=\"text-align:center;\"> 0.051 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> -0.094 </td>\n   <td style=\"text-align:center;\"> -0.085 </td>\n   <td style=\"text-align:center;\"> -0.02 </td>\n   <td style=\"text-align:center;\"> 0.097 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> 0.172 </td>\n   <td style=\"text-align:center;\"> 0.075 </td>\n   <td style=\"text-align:center;\"> 0.151 </td>\n   <td style=\"text-align:center;\"> 0.158 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_loc\n[1] \"0.559\"  \"0.455\"  \"-0.229\" \"0.269\"  \"-0.031\"\n\n$beta_scale\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> -0.24 </td>\n   <td style=\"text-align:center;\"> -0.012 </td>\n   <td style=\"text-align:center;\"> 0.136 </td>\n   <td style=\"text-align:center;\"> -0.169 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> -0.488 </td>\n   <td style=\"text-align:center;\"> 0.837 </td>\n   <td style=\"text-align:center;\"> 0.28 </td>\n   <td style=\"text-align:center;\"> -0.097 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> -0.198 </td>\n   <td style=\"text-align:center;\"> -0.037 </td>\n   <td style=\"text-align:center;\"> -0.151 </td>\n   <td style=\"text-align:center;\"> -0.098 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> 0.221 </td>\n   <td style=\"text-align:center;\"> -0.02 </td>\n   <td style=\"text-align:center;\"> 0.056 </td>\n   <td style=\"text-align:center;\"> -0.004 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> -0.128 </td>\n   <td style=\"text-align:center;\"> 0.01 </td>\n   <td style=\"text-align:center;\"> -0.026 </td>\n   <td style=\"text-align:center;\"> -0.282 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_scale\n[1] \"0.492\"  \"-0.675\" \"-0.42\"  \"0.133\"  \"0.057\" \n\n$shape1\n[1] \"12.379\"\n\n$shape2\n[1] \"1.169\"\n\n$beta_tail_scale\n[1] \"0.096\"  \"-0.163\" \"0.083\"  \"0.089\" \n\n$tail_shape\n[1] \"0.027\"\n\n[control]\nPosterior mean parameters\n\n$alpha\n[1] \"0.213\"\n\n$w\n[1] \"0.958\"\n\n$loc\n[1] \"4.355\"\n\n$scale\n[1] \"1.714\"\n\n$shape1\n[1] \"3.467\"\n\n$shape2\n[1] \"1.418\"\n\n$beta_tail_scale\n[1] \"0.282\"  \"0.147\"  \"0.01\"   \"-0.217\"\n\n$tail_shape\n[1] \"0.026\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsafe_plot(fit_sb_crp, family = c(\"traceplot\", \"autocorrelation\", \"running\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_mean_sb_crp <- predict(fit_sb_crp, x = x_eval, type = \"mean\",\n                            interval = \"credible\", nsim_mean = 100)\nsafe_plot(pred_mean_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-mean-sb-crp-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-mean-sb-crp-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_q_sb_crp <- predict(fit_sb_crp, x = x_eval, type = \"quantile\",\n                         p = 0.5, interval = \"credible\")\nsafe_plot(pred_q_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-quantile-sb-crp-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-quantile-sb-crp-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_d_sb_crp <- predict(fit_sb_crp, x = x_eval, y = y_eval,\n                         type = \"density\", interval = \"credible\")\nsafe_plot(pred_d_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-density-sb-crp-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_surv_sb_crp <- predict(fit_sb_crp, x = x_eval, y = y_eval,\n                            type = \"survival\", interval = \"credible\")\nsafe_plot(pred_surv_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-survival-sb-crp-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_sb_crp <- ate(fit_sb_crp, newdata = x_eval,\n                  interval = \"credible\", nsim_mean = 100)\nsafe_plot(ate_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/ate-sb-crp-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/ate-sb-crp-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqte_sb_crp <- qte(fit_sb_crp, probs = c(0.25, 0.5, 0.75),\n                  newdata = x_eval, interval = \"credible\")\nsafe_plot(qte_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/qte-sb-crp-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/qte-sb-crp-2.png){width=672}\n:::\n:::\n\n\n---\n\n## Model B: Treated CRP, Control SB (Amoroso + GPD)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbundle_crp_sb <- build_causal_bundle(\n  y = y,\n  T = T,\n  X = X,\n  kernel = c(\"amoroso\", \"amoroso\"),\n  backend = c(\"crp\", \"sb\"),\n  PS = \"logit\",\n  GPD = c(TRUE, TRUE),\n  components = c(5, 5),\n  param_specs = param_specs_gpd,\n  mcmc_outcome = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 2),\n  mcmc_ps = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 2)\n)\n\nbundle_crp_sb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDPmixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Chinese Restaurant Process </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> amoroso </td>\n   <td style=\"text-align:center;\"> amoroso </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bundle_crp_sb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDPmixGPD causal bundle summary\nDPmixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Chinese Restaurant Process </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> amoroso </td>\n   <td style=\"text-align:center;\"> amoroso </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_crp_sb <- run_mcmc_causal(bundle_crp_sb)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: beta\n===== Samplers =====\nRW sampler (5)\n  - beta[]  (5 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|-------------|-------------|-------------|-------------|\n|-------------------------------------------------------|\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_loc, beta_ps_loc, beta_ps_scale, beta_scale, beta_tail_scale, shape1, shape2, tail_shape, threshold, w, z\n===== Samplers =====\nRW sampler (71)\n  - alpha\n  - shape1[]  (5 elements)\n  - shape2[]  (5 elements)\n  - beta_loc[]  (20 elements)\n  - beta_ps_loc[]  (5 elements)\n  - beta_scale[]  (20 elements)\n  - beta_ps_scale[]  (5 elements)\n  - threshold\n  - beta_tail_scale[]  (4 elements)\n  - tail_shape\n  - v[]  (4 elements)\ncategorical sampler (232)\n  - z[]  (232 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] To calculate WAIC, set 'WAIC = TRUE', in addition to having enabled WAIC in building the MCMC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating WAIC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] 'ps' is provided in 'data' but is not a variable in the model and is being ignored.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_tail_scale, loc, scale, shape1, shape2, tail_shape, threshold, z\n===== Samplers =====\nRW sampler (6)\n  - threshold\n  - beta_tail_scale[]  (4 elements)\n  - tail_shape\nCRP_concentration sampler (1)\n  - alpha\nCRP_cluster_wrapper sampler (20)\n  - loc[]  (5 elements)\n  - scale[]  (5 elements)\n  - shape1[]  (5 elements)\n  - shape2[]  (5 elements)\nCRP sampler (1)\n  - z[1:268] \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] sampler_CRP: The number of clusters based on the cluster parameters\n            is less than the number of potential clusters. The MCMC is not\n            strictly valid if it ever proposes more components than cluster\n            parameters exist; NIMBLE will warn you if this occurs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] To calculate WAIC, set 'WAIC = TRUE', in addition to having enabled WAIC in building the MCMC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [Warning] CRP_sampler: This MCMC is not for a proper model. The MCMC attempted to use more components than the number of cluster parameters. Please increase the number of cluster parameters.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating WAIC.\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_crp_sb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-- PS fit --\nDPmixGPD PS fit\nmodel: logit \n\n-- Outcome fits --\n[control]\nMixGPD fit | backend: Stick-Breaking Process | kernel: Amoroso Distribution | GPD tail: TRUE\nn = 232 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n\n[treated]\nMixGPD fit | backend: Chinese Restaurant Process | kernel: Amoroso Distribution | GPD tail: TRUE\nn = 268 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n```\n\n\n:::\n\n```{.r .cell-code}\nparams(fit_crp_sb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPosterior mean parameters (causal)\n\n[treated]\nPosterior mean parameters\n\n$alpha\n[1] \"0.691\"\n\n$w\n[1] \"0.576\" \"0.281\"\n\n$loc\n[1] \"5.372\" \"5.853\"\n\n$scale\n[1] \"1.399\" \"2.547\"\n\n$shape1\n[1] \"3.334\" \"2.585\"\n\n$shape2\n[1] \"1.432\" \"3.089\"\n\n$beta_tail_scale\n[1] \"0.068\"  \"-0.026\" \"0.101\"  \"-0.118\"\n\n$tail_shape\n[1] \"-0.07\"\n\n[control]\nPosterior mean parameters\n\n$alpha\n[1] \"0.523\"\n\n$w\n[1] \"0.807\"\n\n$beta_loc\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> 0.051 </td>\n   <td style=\"text-align:center;\"> 0.009 </td>\n   <td style=\"text-align:center;\"> -0.04 </td>\n   <td style=\"text-align:center;\"> 0.335 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> -0.168 </td>\n   <td style=\"text-align:center;\"> 0.107 </td>\n   <td style=\"text-align:center;\"> 0.507 </td>\n   <td style=\"text-align:center;\"> 0.044 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> -0.363 </td>\n   <td style=\"text-align:center;\"> -0.699 </td>\n   <td style=\"text-align:center;\"> -0.424 </td>\n   <td style=\"text-align:center;\"> 1.868 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> -0.126 </td>\n   <td style=\"text-align:center;\"> -0.165 </td>\n   <td style=\"text-align:center;\"> 0.151 </td>\n   <td style=\"text-align:center;\"> 0.038 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> 0.042 </td>\n   <td style=\"text-align:center;\"> -0.097 </td>\n   <td style=\"text-align:center;\"> -0.001 </td>\n   <td style=\"text-align:center;\"> 0.249 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_loc\n[1] \"-0.149\" \"-0.208\" \"0.266\"  \"-0.126\" \"-0.033\"\n\n$beta_scale\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> -0.293 </td>\n   <td style=\"text-align:center;\"> -0.109 </td>\n   <td style=\"text-align:center;\"> 0.197 </td>\n   <td style=\"text-align:center;\"> 0.709 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> -0.307 </td>\n   <td style=\"text-align:center;\"> -0.183 </td>\n   <td style=\"text-align:center;\"> -0.237 </td>\n   <td style=\"text-align:center;\"> 0.322 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> -0.848 </td>\n   <td style=\"text-align:center;\"> -0.58 </td>\n   <td style=\"text-align:center;\"> 0.413 </td>\n   <td style=\"text-align:center;\"> -0.741 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> -0.096 </td>\n   <td style=\"text-align:center;\"> -0.104 </td>\n   <td style=\"text-align:center;\"> -0.213 </td>\n   <td style=\"text-align:center;\"> 0.152 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> -0.035 </td>\n   <td style=\"text-align:center;\"> -0.016 </td>\n   <td style=\"text-align:center;\"> -0.094 </td>\n   <td style=\"text-align:center;\"> 0.038 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_scale\n[1] \"0.153\"  \"-0.09\"  \"1.929\"  \"-0.018\" \"-0.111\"\n\n$shape1\n[1] \"8.717\"\n\n$shape2\n[1] \"0.699\"\n\n$beta_tail_scale\n[1] \"-0.093\" \"0.01\"   \"-0.06\"  \"1.074\" \n\n$tail_shape\n[1] \"-0.001\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsafe_plot(fit_crp_sb, family = c(\"density\", \"geweke\", \"caterpillar\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\nℹ The deprecated feature was likely used in the ggmcmc package.\n  Please report the issue at <https://github.com/xfim/ggmcmc/issues/>.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_mean_crp_sb <- predict(fit_crp_sb, x = x_eval, type = \"mean\",\n                            interval = \"credible\", nsim_mean = 100)\nsafe_plot(pred_mean_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-mean-crp-sb-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-mean-crp-sb-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_q_crp_sb <- predict(fit_crp_sb, x = x_eval, type = \"quantile\",\n                         p = 0.5, interval = \"credible\")\nsafe_plot(pred_q_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-quantile-crp-sb-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-quantile-crp-sb-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_d_crp_sb <- predict(fit_crp_sb, x = x_eval, y = y_eval,\n                         type = \"density\", interval = \"credible\")\nsafe_plot(pred_d_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-density-crp-sb-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_surv_crp_sb <- predict(fit_crp_sb, x = x_eval, y = y_eval,\n                            type = \"survival\", interval = \"credible\")\nsafe_plot(pred_surv_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/predict-survival-crp-sb-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_crp_sb <- ate(fit_crp_sb, newdata = x_eval,\n                  interval = \"credible\", nsim_mean = 100)\nsafe_plot(ate_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/ate-crp-sb-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/ate-crp-sb-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqte_crp_sb <- qte(fit_crp_sb, probs = c(0.25, 0.5, 0.75),\n                  newdata = x_eval, interval = \"credible\")\nsafe_plot(qte_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/qte-crp-sb-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex19-causal-different-backends-SB_files/figure-html/qte-crp-sb-2.png){width=672}\n:::\n:::\n\n\n---\n\n<!-- workflow-nav:start -->\n## Workflow Navigation\n\n- Previous: [ex18-causal-different-backends-CRP](ex18-causal-different-backends-CRP.html)\n- Next: [ex20-troubleshooting](ex20-troubleshooting.html)\n- Workflow index: [Roadmap](../roadmap.html)\n- Practical entry: [Examples](../Examples/index.html)\n<!-- workflow-nav:end -->\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}