comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%

ignore:
  - "R/zzz.R"
  - "tests/"
  - "inst/"

flags:
  ubuntu-latest-Rrelease:
    carryforward: false
  ubuntu-latest-Rdevel:
    carryforward: false
  macos-latest-Rrelease:
    carryforward: false
  windows-latest-Rrelease:
    carryforward: false
