comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: auto
        threshold: 2%
        base: auto
  ignore:
    - "R/00-kernel-registry.R"
    - "R/globals.R"

flags:
  ubuntu-latest-Rrelease:
    carryforward: false
  ubuntu-latest-Rdevel:
    carryforward: false
  macos-latest-Rrelease:
    carryforward: false
  windows-latest-Rrelease:
    carryforward: false
codecov:
 token: 527215a4-d374-43a0-acf9-1cc42bbfaa75
