codecov:
  max_report_age: off

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: auto
        threshold: 2%
        base: auto
  ignore:
    - "R/00-kernel-registry.R"
    - "R/globals.R"
    - "R/Utility.R"
    - "**/R/00-kernel-registry.R"
    - "**/R/globals.R"
    - "**/R/Utility.R"

flags:
  ubuntu-latest-Rrelease:
    carryforward: false
  ubuntu-latest-Rdevel:
    carryforward: false
  macos-latest-Rrelease:
    carryforward: false
  windows-latest-Rrelease:
    carryforward: false
