{
  "hash": "5575d8c5d7b548a40b993973ddfd0d31",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ex18. Causal Inference: Mixed Backends (Bulk-only) - Cauchy Kernel\"\n---\n\n\n\n\n> **Legacy vignette (for the website / historical notes).**\n> These files may not match the current exported API one-to-one.\n> Last verified: **2026-01-18**.\n>\n> For the up-to-date workflow, see the main package vignettes (basic, unconditional, conditional, and causal)..\n\n\n# Causal Inference: Mixed Backends (Bulk-only) - Cauchy Kernel {#causal-different-backends-bulk}\n\nThis vignette fits two mixed-backend causal models with a shared Cauchy kernel:\n\n- Model A: Treated = SB, Control = CRP\n- Model B: Treated = CRP, Control = SB\n\n---\n\n## Data Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"causal_alt_real500_p4_k2\", package = \"CausalMixGPD\")\ny <- causal_alt_real500_p4_k2$y\nT <- causal_alt_real500_p4_k2$T\nX <- as.matrix(causal_alt_real500_p4_k2$X)\n\nsummary_tbl <- tibble(\n  statistic = c(\"N\", \"Mean\", \"SD\", \"Min\", \"Max\"),\n  value = c(length(y), mean(y), sd(y), min(y), max(y))\n)\n\nsummary_tbl %>%\n  mutate(value = signif(value, 4)) %>%\n  kable(caption = \"Outcome Summary (Cauchy)\", align = \"c\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE, position = \"center\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Outcome Summary (Cauchy)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> statistic </th>\n   <th style=\"text-align:center;\"> value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> N </td>\n   <td style=\"text-align:center;\"> 500.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Mean </td>\n   <td style=\"text-align:center;\"> 0.274 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> SD </td>\n   <td style=\"text-align:center;\"> 1.764 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Min </td>\n   <td style=\"text-align:center;\"> -8.089 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Max </td>\n   <td style=\"text-align:center;\"> 5.275 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\nx_eval <- X[1:40, , drop = FALSE]\ny_eval <- y[1:40]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_causal <- data.frame(y = y, T = as.factor(T), x1 = X[, 1])\n\np_scatter <- ggplot(df_causal, aes(x = x1, y = y, color = T)) +\n  geom_point(alpha = 0.5) +\n  labs(title = \"Outcome vs X1\", x = \"X1\", y = \"y\", color = \"Treatment\") +\n  theme_minimal()\n\np_scatter\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/data-scatter-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Model A: Treated SB, Control CRP (Cauchy)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbundle_sb_crp <- build_causal_bundle(\n  y = y,\n  T = T,\n  X = X,\n  kernel = c(\"cauchy\", \"cauchy\"),\n  backend = c(\"sb\", \"crp\"),\n  PS = \"logit\",\n  GPD = c(FALSE, FALSE),\n  components = c(5, 5),\n  mcmc_outcome = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 1),\n  mcmc_ps = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 1)\n)\n\nbundle_sb_crp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCausalMixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n   <td style=\"text-align:center;\"> Chinese Restaurant Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> cauchy </td>\n   <td style=\"text-align:center;\"> cauchy </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bundle_sb_crp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCausalMixGPD causal bundle summary\nCausalMixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n   <td style=\"text-align:center;\"> Chinese Restaurant Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> cauchy </td>\n   <td style=\"text-align:center;\"> cauchy </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_sb_crp <- run_mcmc_causal(bundle_sb_crp)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: beta\n===== Samplers =====\nRW sampler (5)\n  - beta[]  (5 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|-------------|-------------|-------------|-------------|\n|-------------------------------------------------------|\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] 'P' is provided in 'constants' but not used in the model code and is being ignored.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] Registering 'dCauchy' as a distribution based on its use in BUGS code. If you make changes to the nimbleFunctions for the distribution, you must call 'deregisterDistributions' before using the distribution in BUGS code for those changes to take effect.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] 'X' is provided in 'data' but is not a variable in the model and is being ignored.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] 'ps' is provided in 'data' but is not a variable in the model and is being ignored.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, location, scale, z\n===== Samplers =====\nCRP_concentration sampler (1)\n  - alpha\nCRP_cluster_wrapper sampler (10)\n  - location[]  (5 elements)\n  - scale[]  (5 elements)\nCRP sampler (1)\n  - z[1:232] \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] sampler_CRP: The number of clusters based on the cluster parameters\n            is less than the number of potential clusters. The MCMC is not\n            strictly valid if it ever proposes more components than cluster\n            parameters exist; NIMBLE will warn you if this occurs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] To calculate WAIC, set 'WAIC = TRUE', in addition to having enabled WAIC in building the MCMC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [Warning] CRP_sampler: This MCMC is not for a proper model. The MCMC attempted to use more components than the number of cluster parameters. Please increase the number of cluster parameters.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating WAIC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_location, beta_ps_location, scale, w, z\n===== Samplers =====\nRW sampler (35)\n  - alpha\n  - scale[]  (5 elements)\n  - beta_location[]  (20 elements)\n  - beta_ps_location[]  (5 elements)\n  - v[]  (4 elements)\ncategorical sampler (268)\n  - z[]  (268 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] To calculate WAIC, set 'WAIC = TRUE', in addition to having enabled WAIC in building the MCMC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating WAIC.\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_sb_crp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-- PS fit --\nCausalMixGPD PS fit\nmodel: logit \n\n-- Outcome fits --\n[control]\nMixGPD fit | backend: Chinese Restaurant Process | kernel: Cauchy Distribution | GPD tail: FALSE\nn = 232 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n\n[treated]\nMixGPD fit | backend: Stick-Breaking Process | kernel: Cauchy Distribution | GPD tail: FALSE\nn = 268 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n```\n\n\n:::\n\n```{.r .cell-code}\nparams(fit_sb_crp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPosterior mean parameters (causal)\n\n[treated]\nPosterior mean parameters\n\n$alpha\n[1] \"1.89\"\n\n$w\n[1] \"0.37\"  \"0.249\" \"0.192\"\n\n$beta_location\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> 0.134 </td>\n   <td style=\"text-align:center;\"> -0.822 </td>\n   <td style=\"text-align:center;\"> 0.699 </td>\n   <td style=\"text-align:center;\"> 0.717 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> -0.512 </td>\n   <td style=\"text-align:center;\"> 0.661 </td>\n   <td style=\"text-align:center;\"> 0.912 </td>\n   <td style=\"text-align:center;\"> 1.235 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> -0.811 </td>\n   <td style=\"text-align:center;\"> 0.572 </td>\n   <td style=\"text-align:center;\"> 0.085 </td>\n   <td style=\"text-align:center;\"> -0.783 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> 0.404 </td>\n   <td style=\"text-align:center;\"> -1.122 </td>\n   <td style=\"text-align:center;\"> 0.07 </td>\n   <td style=\"text-align:center;\"> 0.48 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> -0.026 </td>\n   <td style=\"text-align:center;\"> -0.705 </td>\n   <td style=\"text-align:center;\"> -0.908 </td>\n   <td style=\"text-align:center;\"> 0.336 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_location\n[1] \"0.524\"  \"0.467\"  \"0.856\"  \"0.422\"  \"-0.441\"\n\n$scale\n[1] \"0.653\" \"0.565\" \"0.53\" \n\n[control]\nPosterior mean parameters\n\n$alpha\n[1] \"0.632\"\n\n$w\n[1] \"0.417\" \"0.302\" \"0.219\"\n\n$location\n[1] \"-0.046\" \"0.662\"  \"-0.17\" \n\n$scale\n[1] \"0.524\" \"0.523\" \"0.418\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsafe_plot(fit_sb_crp, family = c(\"traceplot\", \"autocorrelation\", \"running\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_mean_sb_crp <- predict(fit_sb_crp, x = x_eval, type = \"mean\",\n                            interval = \"credible\", nsim_mean = 100)\nsafe_plot(pred_mean_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-mean-sb-crp-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-mean-sb-crp-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_q_sb_crp <- predict(fit_sb_crp, x = x_eval, type = \"quantile\",\n                         p = 0.5, interval = \"credible\")\nsafe_plot(pred_q_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-quantile-sb-crp-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-quantile-sb-crp-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_d_sb_crp <- predict(fit_sb_crp, x = x_eval, y = y_eval,\n                         type = \"density\", interval = \"credible\")\nsafe_plot(pred_d_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-density-sb-crp-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_surv_sb_crp <- predict(fit_sb_crp, x = x_eval, y = y_eval,\n                            type = \"survival\", interval = \"credible\")\nsafe_plot(pred_surv_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-survival-sb-crp-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_sb_crp <- ate(fit_sb_crp, newdata = x_eval,\n                  interval = \"credible\", nsim_mean = 100)\nsafe_plot(ate_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/ate-sb-crp-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/ate-sb-crp-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqte_sb_crp <- qte(fit_sb_crp, probs = c(0.25, 0.5, 0.75),\n                  newdata = x_eval, interval = \"credible\")\nsafe_plot(qte_sb_crp)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/qte-sb-crp-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/qte-sb-crp-2.png){width=672}\n:::\n:::\n\n\n---\n\n## Model B: Treated CRP, Control SB (Cauchy)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbundle_crp_sb <- build_causal_bundle(\n  y = y,\n  T = T,\n  X = X,\n  kernel = c(\"cauchy\", \"cauchy\"),\n  backend = c(\"crp\", \"sb\"),\n  PS = \"logit\",\n  GPD = c(FALSE, FALSE),\n  components = c(5, 5),\n  mcmc_outcome = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 2),\n  mcmc_ps = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 2)\n)\n\nbundle_crp_sb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCausalMixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Chinese Restaurant Process </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> cauchy </td>\n   <td style=\"text-align:center;\"> cauchy </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bundle_crp_sb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCausalMixGPD causal bundle summary\nCausalMixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Chinese Restaurant Process </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> cauchy </td>\n   <td style=\"text-align:center;\"> cauchy </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_crp_sb <- run_mcmc_causal(bundle_crp_sb)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: beta\n===== Samplers =====\nRW sampler (5)\n  - beta[]  (5 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|-------------|-------------|-------------|-------------|\n|-------------------------------------------------------|\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] This model is not fully initialized. This is not an error.\n         To see which variables are not initialized, use model$initializeInfo().\n         For more information on model initialization, see help(modelInitialization).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_location, beta_ps_location, scale, w, z\n===== Samplers =====\nRW sampler (35)\n  - alpha\n  - scale[]  (5 elements)\n  - beta_location[]  (20 elements)\n  - beta_ps_location[]  (5 elements)\n  - v[]  (4 elements)\ncategorical sampler (232)\n  - z[]  (232 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] To calculate WAIC, set 'WAIC = TRUE', in addition to having enabled WAIC in building the MCMC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating WAIC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDefining model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] 'P' is provided in 'constants' but not used in the model code and is being ignored.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBuilding model\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting data and initial values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] 'X' is provided in 'data' but is not a variable in the model and is being ignored.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Note] 'ps' is provided in 'data' but is not a variable in the model and is being ignored.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model sizes and dimensions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking model calculations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, location, scale, z\n===== Samplers =====\nCRP_concentration sampler (1)\n  - alpha\nCRP_cluster_wrapper sampler (10)\n  - location[]  (5 elements)\n  - scale[]  (5 elements)\nCRP sampler (1)\n  - z[1:268] \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] sampler_CRP: The number of clusters based on the cluster parameters\n            is less than the number of potential clusters. The MCMC is not\n            strictly valid if it ever proposes more components than cluster\n            parameters exist; NIMBLE will warn you if this occurs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  [Warning] To calculate WAIC, set 'WAIC = TRUE', in addition to having enabled WAIC in building the MCMC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning chain 1...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [Warning] CRP_sampler: This MCMC is not for a proper model. The MCMC attempted to use more components than the number of cluster parameters. Please increase the number of cluster parameters.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling\n  [Note] This may take a minute.\n  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating WAIC.\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_crp_sb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-- PS fit --\nCausalMixGPD PS fit\nmodel: logit \n\n-- Outcome fits --\n[control]\nMixGPD fit | backend: Stick-Breaking Process | kernel: Cauchy Distribution | GPD tail: FALSE\nn = 232 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n\n[treated]\nMixGPD fit | backend: Chinese Restaurant Process | kernel: Cauchy Distribution | GPD tail: FALSE\nn = 268 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n```\n\n\n:::\n\n```{.r .cell-code}\nparams(fit_crp_sb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPosterior mean parameters (causal)\n\n[treated]\nPosterior mean parameters\n\n$alpha\n[1] \"0.462\"\n\n$w\n[1] \"0.526\" \"0.436\"\n\n$location\n[1] \"0.674\"  \"-0.155\"\n\n$scale\n[1] \"0.627\" \"0.522\"\n\n[control]\nPosterior mean parameters\n\n$alpha\n[1] \"1.163\"\n\n$w\n[1] \"0.441\" \"0.311\" \"0.209\"\n\n$beta_location\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> 0.745 </td>\n   <td style=\"text-align:center;\"> 0.301 </td>\n   <td style=\"text-align:center;\"> -0.86 </td>\n   <td style=\"text-align:center;\"> -0.321 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> 1.087 </td>\n   <td style=\"text-align:center;\"> 0.918 </td>\n   <td style=\"text-align:center;\"> -0.52 </td>\n   <td style=\"text-align:center;\"> -0.032 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> 0.085 </td>\n   <td style=\"text-align:center;\"> 0.023 </td>\n   <td style=\"text-align:center;\"> -0.235 </td>\n   <td style=\"text-align:center;\"> 2.471 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> 0.104 </td>\n   <td style=\"text-align:center;\"> 0.364 </td>\n   <td style=\"text-align:center;\"> 0.011 </td>\n   <td style=\"text-align:center;\"> 0.179 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> -0.729 </td>\n   <td style=\"text-align:center;\"> 0.61 </td>\n   <td style=\"text-align:center;\"> -0.206 </td>\n   <td style=\"text-align:center;\"> 0.869 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_location\n[1] \"-1.636\" \"-2.537\" \"-0.81\"  \"0.196\"  \"-0.122\"\n\n$scale\n[1] \"0.685\" \"0.612\" \"0.495\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsafe_plot(fit_crp_sb, family = c(\"density\", \"geweke\", \"caterpillar\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\nℹ The deprecated feature was likely used in the ggmcmc package.\n  Please report the issue at <https://github.com/xfim/ggmcmc/issues/>.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_mean_crp_sb <- predict(fit_crp_sb, x = x_eval, type = \"mean\",\n                            interval = \"credible\", nsim_mean = 100)\nsafe_plot(pred_mean_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-mean-crp-sb-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-mean-crp-sb-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_q_crp_sb <- predict(fit_crp_sb, x = x_eval, type = \"quantile\",\n                         p = 0.5, interval = \"credible\")\nsafe_plot(pred_q_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-quantile-crp-sb-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-quantile-crp-sb-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_d_crp_sb <- predict(fit_crp_sb, x = x_eval, y = y_eval,\n                         type = \"density\", interval = \"credible\")\nsafe_plot(pred_d_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-density-crp-sb-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_surv_crp_sb <- predict(fit_crp_sb, x = x_eval, y = y_eval,\n                            type = \"survival\", interval = \"credible\")\nsafe_plot(pred_surv_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/predict-survival-crp-sb-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_crp_sb <- ate(fit_crp_sb, newdata = x_eval,\n                  interval = \"credible\", nsim_mean = 100)\nsafe_plot(ate_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/ate-crp-sb-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/ate-crp-sb-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqte_crp_sb <- qte(fit_crp_sb, probs = c(0.25, 0.5, 0.75),\n                  newdata = x_eval, interval = \"credible\")\nsafe_plot(qte_crp_sb)\n```\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/qte-crp-sb-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ex18-causal-different-backends-CRP_files/figure-html/qte-crp-sb-2.png){width=672}\n:::\n:::\n\n\n---\n\n<!-- workflow-nav:start -->\n## Workflow Navigation\n\n- Previous: [ex17-causal-same-backend-SB](ex17-causal-same-backend-SB.html)\n- Next: [ex19-causal-different-backends-SB](ex19-causal-different-backends-SB.html)\n- Workflow index: [Roadmap](../roadmap.html)\n- Practical entry: [Examples](../Examples/index.html)\n<!-- workflow-nav:end -->\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}