project:
  type: website
  output-dir: ../docs

website:
  title: "DPmixGPD"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: Cookbook
        href: cookbook/index.html
      - text: Kernels
        href: kernels/index.html
      - text: Reference
        href: reference/index.html
      - text: Roadmap
        href: roadmap.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
