---
title: "Causal modeling quickstart"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Causal modeling quickstart}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE,
  cache.path = "cache/causal-",
  warning = FALSE,
  message = FALSE
)
```

```{r libraries}
library(DPmixGPD)
library(nimble)
use_cached_fit <- TRUE
.fit_path <- function(name) {
  path <- system.file("extdata", name, package = "DPmixGPD")
  if (path == "") path <- file.path("inst", "extdata", name)
  path
}
fit_causal_con <- readRDS(.fit_path("fit_causal_con.rds"))
fit_causal_trt <- readRDS(.fit_path("fit_causal_trt.rds"))
fit_causal_meta <- readRDS(.fit_path("fit_causal_meta.rds"))
fit_causal_small <- list(
  ps_fit = NULL,
  outcome_fit = list(con = fit_causal_con, trt = fit_causal_trt),
  bundle = fit_causal_meta,
  call = NULL
)
class(fit_causal_small) <- "dpmixgpd_causal_fit"
```

```{r data}
set.seed(1)
dat <- sim_causal_qte(n = 120)
X <- dat$X
T <- dat$t
y <- dat$y

cb <- build_causal_bundle(
  y = y,
  X = X,
  T = T,
  backend = c("sb", "sb"),
  kernel = c("normal", "normal"),
  GPD = c(FALSE, FALSE),
  J = c(8, 8),
  mcmc_outcome = list(niter = 200, nburnin = 50, thin = 1, nchains = 1, seed = 1),
  mcmc_ps = list(niter = 200, nburnin = 50, thin = 1, nchains = 1, seed = 1)
)
```

```{r fit}
if (use_cached_fit) {
  cf <- fit_causal_small
} else {
  cf <- run_mcmc_causal(cb, show_progress = FALSE)
}
summary(cf$outcome_fit$trt)
newdata <- if (use_cached_fit && !is.null(cf$bundle$X)) cf$bundle$X else X
```

```{r quantiles}
pr_trt <- predict(cf$outcome_fit$trt, type = "quantile", p = c(0.5, 0.9), newdata = newdata)
pr_con <- predict(cf$outcome_fit$con, type = "quantile", p = c(0.5, 0.9), newdata = newdata)

pr_trt$fit
pr_con$fit
```

```{r qte}
qt <- qte(cf, probs = c(0.5, 0.9), newdata = newdata)
qt$fit

qs <- c(0.1, 0.5, 0.9)
qt2 <- qte(cf, probs = qs, newdata = newdata)
plot(qs, as.numeric(qt2$fit[1, ]), type = "b",
     xlab = "quantile", ylab = "QTE",
     main = "Quantile treatment effect")
```

```{r session}
sessionInfo()
```