---
title: "Kernel: Laplace"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Kernel: Laplace}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE,
  cache.path = "cache/kernel-laplace-",
  warning = FALSE,
  message = FALSE
)
```

```{r kernel-laplace}
library(DPmixGPD)
library(nimble)
use_cached_fit <- TRUE
.fit_path <- function(name) {
  path <- system.file("extdata", name, package = "DPmixGPD")
  if (path == "") path <- file.path("inst", "extdata", name)
  path
}
fit_small <- readRDS(.fit_path("fit_small.rds"))
w <- c(0.5, 0.5)
location <- c(-0.5, 0.5)
scale <- c(0.6, 1.1)

x <- 0.2
p <- 0.9

dLaplaceMix(x, w = w, location = location, scale = scale, log = FALSE)
pLaplaceMix(x, w = w, location = location, scale = scale, lower.tail = TRUE, log.p = FALSE)
qLaplaceMix(p, w = w, location = location, scale = scale)

threshold <- 0.3
tail_scale <- 1.0
tail_shape <- 0.2

dLaplaceMixGpd(x, w = w, location = location, scale = scale,
               threshold = threshold, tail_scale = tail_scale, tail_shape = tail_shape)
qLaplaceMixGpd(0.99, w = w, location = location, scale = scale,
               threshold = threshold, tail_scale = tail_scale, tail_shape = tail_shape)

set.seed(1)
y <- rexp(30)

bundle <- build_nimble_bundle(
  y = y,
  backend = "sb",
  kernel = "laplace",
  GPD = TRUE,
  J = 6
)

bundle$spec$meta
```

```{r session}
sessionInfo()
```
