# Combined tests from ci/
# Auto-generated by workspace refactor script

# ===== BEGIN ci/test-site-map-tools.R =====
skip_if_not_test_level("ci")

find_package_root <- function() {
  current <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
  for (i in 0:8) {
    candidate <- current
    if (file.exists(file.path(candidate, "DESCRIPTION"))) {
      return(candidate)
    }
    current <- dirname(current)
  }
  stop("Could not locate package root for site-map tests.")
}

pkg_root <- find_package_root()
source(file.path(pkg_root, "tools", "site-map", "extract_site_map.R"), local = TRUE)
source(file.path(pkg_root, "tools", "site-map", "analyze_site_map.R"), local = TRUE)

write_fixture_file <- function(path, lines) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, con = path, useBytes = TRUE)
}

make_workflow_pages <- function(docs_root, break_chain = FALSE) {
  for (i in 1:20) {
    file_path <- file.path(docs_root, "workflows", sprintf("v%02d-topic.html", i))
    link_html <- ""
    if (i < 20) {
      if (!(break_chain && i == 10)) {
        link_html <- sprintf("<a href=\"v%02d-topic.html\">next</a>", i + 1L)
      }
    }
    write_fixture_file(
      file_path,
      c(
        "<html><body>",
        sprintf("<h1>v%02d</h1>", i),
        link_html,
        "</body></html>"
      )
    )
  }
}

test_that("extract_site_map handles strict internal links and normalization", {
  tmp_root <- tempfile("site_map_extract_")
  docs_root <- file.path(tmp_root, "docs")
  out_root <- file.path(tmp_root, "out")
  dir.create(docs_root, recursive = TRUE, showWarnings = FALSE)

  write_fixture_file(
    file.path(docs_root, "index.html"),
    c(
      "<html><body>",
      "<a href=\"workflows/v01-start-here.html\">workflow</a>",
      "<a href=\"missing-page.html\">broken</a>",
      "<a href=\"workflows/\">workflows-dir</a>",
      "<a href=\"https://example.com\">external</a>",
      "<a href=\"mailto:test@example.com\">mail</a>",
      "<a href=\"javascript:void(0)\">js</a>",
      "<a href=\"#top\">anchor</a>",
      "</body></html>"
    )
  )
  write_fixture_file(
    file.path(docs_root, "workflows", "index.html"),
    c("<html><body>", "<a href=\"../index.html\">home</a>", "</body></html>")
  )
  write_fixture_file(
    file.path(docs_root, "workflows", "v01-start-here.html"),
    c(
      "<html><body>",
      "<a href=\"../index.html#intro\">back-home</a>",
      "<a href=\"v02-introduction\">next-no-ext</a>",
      "</body></html>"
    )
  )
  write_fixture_file(
    file.path(docs_root, "workflows", "v02-introduction.html"),
    c("<html><body>", "ok", "</body></html>")
  )

  extract_site_map(site_root = docs_root, output_dir = out_root, verbose = FALSE)
  edges <- read.csv(file.path(out_root, "website_link_edges.csv"), stringsAsFactors = FALSE)

  expect_true(any(edges$href_raw == "missing-page.html" & !as.logical(edges$target_exists)))
  expect_true(any(edges$href_raw == "../index.html#intro" & edges$target == "index.html"))
  expect_true(any(edges$href_raw == "v02-introduction" & edges$target == "workflows/v02-introduction.html"))
  expect_true(any(edges$href_raw == "workflows/" & edges$target == "workflows/index.html"))

  # External/anchor hrefs are intentionally ignored by extractor.
  expect_false(any(grepl("^https?://", edges$href_raw)))
  expect_false(any(grepl("^mailto:", edges$href_raw)))
  expect_false(any(grepl("^javascript:", edges$href_raw)))
  expect_false(any(grepl("^#", edges$href_raw)))
})

test_that("analyze_site_map gate follows broken-link and workflow-chain policy", {
  tmp_root <- tempfile("site_map_analyze_")
  docs_root <- file.path(tmp_root, "docs")
  out_root <- file.path(tmp_root, "out")
  dir.create(docs_root, recursive = TRUE, showWarnings = FALSE)

  write_fixture_file(
    file.path(docs_root, "index.html"),
    c(
      "<html><body>",
      "<a href=\"workflows/v01-topic.html\">start</a>",
      "</body></html>"
    )
  )
  make_workflow_pages(docs_root = docs_root, break_chain = FALSE)

  extract_site_map(site_root = docs_root, output_dir = out_root, verbose = FALSE)
  ok_result <- analyze_site_map(site_root = docs_root, output_dir = out_root, verbose = FALSE)

  expect_true(isTRUE(ok_result$summary$gate_pass))
  expect_equal(ok_result$summary$broken_link_count, 0)
  expect_equal(ok_result$summary$workflow_chain_break_count, 0)

  # Rebuild with a broken chain and a broken link.
  unlink(tmp_root, recursive = TRUE, force = TRUE)
  dir.create(docs_root, recursive = TRUE, showWarnings = FALSE)
  write_fixture_file(
    file.path(docs_root, "index.html"),
    c(
      "<html><body>",
      "<a href=\"workflows/v01-topic.html\">start</a>",
      "<a href=\"does-not-exist.html\">broken</a>",
      "</body></html>"
    )
  )
  make_workflow_pages(docs_root = docs_root, break_chain = TRUE)

  extract_site_map(site_root = docs_root, output_dir = out_root, verbose = FALSE)
  bad_result <- analyze_site_map(site_root = docs_root, output_dir = out_root, verbose = FALSE)

  expect_false(isTRUE(bad_result$summary$gate_pass))
  expect_gt(bad_result$summary$broken_link_count, 0)
  expect_gt(bad_result$summary$workflow_chain_break_count, 0)
})

# ===== END ci/test-site-map-tools.R =====


