{
  "hash": "16fe03d80586fdc982957214f8f1c178",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"17. Causal Inference: Same Backend (SB) - Laplace Kernel\"\noutput:\n  rmarkdown::html_vignette:\n    highlight: null\n    code_folding: show\nvignette: >\n  %\\VignetteIndexEntry{17. Causal Inference: Same Backend (SB) - Laplace Kernel}\n  %\\VignetteEngine{knitr::rmarkdown}\n  %\\VignetteEncoding{UTF-8}\n---\n\n\n\n\n> **Legacy vignette (for the website / historical notes).**\n> These files may not match the current exported API one-to-one.\n> Last verified: **2026-01-18**.\n>\n> For the up-to-date workflow, see the main package vignettes (Introduction, Model Spec, MCMC Workflow, Unconditional/Conditional/Causal, Backends, S3 Reference).\n\n\n# Causal Inference: Same Backend (SB) - Laplace Kernel {#causal-sb-same-backend}\n\nThis vignette fits two SB-based causal models using the same kernel (Laplace):\n\n- Model A: bulk-only outcome models (GPD = FALSE)\n- Model B: GPD-augmented outcome models (GPD = TRUE)\n\n---\n\n## Data Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"causal_alt_real500_p4_k2\")\ny <- causal_alt_real500_p4_k2$y\nT <- causal_alt_real500_p4_k2$T\nX <- as.matrix(causal_alt_real500_p4_k2$X)\n\nsummary_tbl <- tibble(\n  statistic = c(\"N\", \"Mean\", \"SD\", \"Min\", \"Max\"),\n  value = c(length(y), mean(y), sd(y), min(y), max(y))\n)\n\nsummary_tbl %>%\n  mutate(value = signif(value, 4)) %>%\n  kable(caption = \"Causal Dataset Summary\", align = \"c\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE, position = \"center\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Causal Dataset Summary</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> statistic </th>\n   <th style=\"text-align:center;\"> value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> N </td>\n   <td style=\"text-align:center;\"> 500.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Mean </td>\n   <td style=\"text-align:center;\"> 0.274 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> SD </td>\n   <td style=\"text-align:center;\"> 1.764 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Min </td>\n   <td style=\"text-align:center;\"> -8.089 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Max </td>\n   <td style=\"text-align:center;\"> 5.275 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\nx_eval <- X[1:40, , drop = FALSE]\ny_eval <- y[1:40]\nu_threshold <- as.numeric(stats::quantile(y, 0.8, names = FALSE))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_causal <- data.frame(y = y, T = as.factor(T), x1 = X[, 1], x2 = X[, 2])\n\np_scatter <- ggplot(df_causal, aes(x = x1, y = y, color = T)) +\n  geom_point(alpha = 0.5) +\n  labs(title = \"Outcome vs X1 by Treatment\", x = \"X1\", y = \"y\", color = \"Treatment\") +\n  theme_minimal()\n\np_scatter\n```\n\n::: {.cell-output-display}\n![](v17-causal-same-backend-SB_files/figure-html/data-scatter-1.png){width=768}\n:::\n:::\n\n\n---\n\n## Model A: SB Bulk-only (Laplace)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbundle_sb_bulk <- build_causal_bundle(\n  y = y,\n  T = T,\n  X = X,\n  kernel = \"laplace\",\n  backend = \"sb\",\n  PS = \"logit\",\n  GPD = FALSE,\n  components = 5,\n  mcmc_outcome = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 1),\n  mcmc_ps = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 1)\n)\n\nbundle_sb_bulk\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDPmixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> laplace </td>\n   <td style=\"text-align:center;\"> laplace </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bundle_sb_bulk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDPmixGPD causal bundle summary\nDPmixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> laplace </td>\n   <td style=\"text-align:center;\"> laplace </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n   <td style=\"text-align:center;\"> FALSE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_sb_bulk <- run_mcmc_causal(bundle_sb_bulk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: beta\n===== Samplers =====\nRW sampler (5)\n  - beta[]  (5 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|-------------|-------------|-------------|-------------|\n|-------------------------------------------------------|\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_location, beta_ps_location, scale, w, z\n===== Samplers =====\nRW sampler (30)\n  - alpha\n  - beta_location[]  (20 elements)\n  - beta_ps_location[]  (5 elements)\n  - v[]  (4 elements)\nconjugate sampler (5)\n  - scale[]  (5 elements)\ncategorical sampler (232)\n  - z[]  (232 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_location, beta_ps_location, scale, w, z\n===== Samplers =====\nRW sampler (30)\n  - alpha\n  - beta_location[]  (20 elements)\n  - beta_ps_location[]  (5 elements)\n  - v[]  (4 elements)\nconjugate sampler (5)\n  - scale[]  (5 elements)\ncategorical sampler (268)\n  - z[]  (268 elements)\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_sb_bulk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-- PS fit --\nDPmixGPD PS fit\nmodel: logit \n\n-- Outcome fits --\n[control]\nMixGPD fit | backend: Stick-Breaking Process | kernel: Laplace Distribution | GPD tail: FALSE\nn = 232 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n\n[treated]\nMixGPD fit | backend: Stick-Breaking Process | kernel: Laplace Distribution | GPD tail: FALSE\nn = 268 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n```\n\n\n:::\n\n```{.r .cell-code}\nparams(fit_sb_bulk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPosterior mean parameters (causal)\n\n[treated]\nPosterior mean parameters\n\n$alpha\n[1] \"2.302\"\n\n$w\n[1] \"0.425\" \"0.277\" \"0.167\"\n\n$beta_location\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> 0.784 </td>\n   <td style=\"text-align:center;\"> -0.463 </td>\n   <td style=\"text-align:center;\"> -0.367 </td>\n   <td style=\"text-align:center;\"> 0.423 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> -0.095 </td>\n   <td style=\"text-align:center;\"> -0.912 </td>\n   <td style=\"text-align:center;\"> -0.267 </td>\n   <td style=\"text-align:center;\"> 0.413 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> 0.123 </td>\n   <td style=\"text-align:center;\"> 0.957 </td>\n   <td style=\"text-align:center;\"> 0.151 </td>\n   <td style=\"text-align:center;\"> 0.093 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> 0.259 </td>\n   <td style=\"text-align:center;\"> -0.217 </td>\n   <td style=\"text-align:center;\"> 0.189 </td>\n   <td style=\"text-align:center;\"> -0.185 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> 0.196 </td>\n   <td style=\"text-align:center;\"> -0.008 </td>\n   <td style=\"text-align:center;\"> 0.386 </td>\n   <td style=\"text-align:center;\"> 0.824 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_location\n[1] \"-0.909\" \"0.361\"  \"-0.23\"  \"0.111\"  \"0.01\"  \n\n$scale\n[1] \"0.863\" \"1.057\" \"1.493\"\n\n[control]\nPosterior mean parameters\n\n$alpha\n[1] \"0.957\"\n\n$w\n[1] \"0.505\" \"0.334\"\n\n$beta_location\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> -0.196 </td>\n   <td style=\"text-align:center;\"> -0.038 </td>\n   <td style=\"text-align:center;\"> -0.248 </td>\n   <td style=\"text-align:center;\"> 1.827 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> 0.472 </td>\n   <td style=\"text-align:center;\"> 0.183 </td>\n   <td style=\"text-align:center;\"> -0.426 </td>\n   <td style=\"text-align:center;\"> -0.217 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> 0.221 </td>\n   <td style=\"text-align:center;\"> 0.405 </td>\n   <td style=\"text-align:center;\"> -0.276 </td>\n   <td style=\"text-align:center;\"> 0.527 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> 0.14 </td>\n   <td style=\"text-align:center;\"> -0.051 </td>\n   <td style=\"text-align:center;\"> 0.024 </td>\n   <td style=\"text-align:center;\"> 0.538 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> -0.551 </td>\n   <td style=\"text-align:center;\"> 0.197 </td>\n   <td style=\"text-align:center;\"> -0.166 </td>\n   <td style=\"text-align:center;\"> -0.241 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_location\n[1] \"-0.21\"  \"-1.001\" \"-0.617\" \"0.064\"  \"0.25\"  \n\n$scale\n[1] \"0.977\" \"1.164\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (interactive()) plot(fit_sb_bulk, family = c(\"traceplot\", \"autocorrelation\", \"running\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_mean_bulk <- predict(fit_sb_bulk, x = x_eval, type = \"mean\",\n                          interval = \"credible\", nsim_mean = 100)\nif (interactive()) plot(pred_mean_bulk)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_q_bulk <- predict(fit_sb_bulk, x = x_eval, type = \"quantile\",\n                       p = 0.5, interval = \"credible\")\nif (interactive()) plot(pred_q_bulk)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_d_bulk <- predict(fit_sb_bulk, x = x_eval, y = y_eval,\n                       type = \"density\", interval = \"credible\")\nif (interactive()) plot(pred_d_bulk)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_surv_bulk <- predict(fit_sb_bulk, x = x_eval, y = y_eval,\n                          type = \"survival\", interval = \"credible\")\nif (interactive()) plot(pred_surv_bulk)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_bulk <- ate(fit_sb_bulk, newdata = x_eval,\n                interval = \"credible\", nsim_mean = 100)\nif (interactive()) plot(ate_bulk)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqte_bulk <- qte(fit_sb_bulk, probs = c(0.25, 0.5, 0.75),\n                newdata = x_eval, interval = \"credible\")\nif (interactive()) plot(qte_bulk)\n```\n:::\n\n\n---\n\n## Model B: SB with GPD Tail (Laplace)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparam_specs_gpd <- list(\n  gpd = list(\n    threshold = list(\n      mode = \"dist\",\n      dist = \"lognormal\",\n      args = list(meanlog = log(max(u_threshold, .Machine$double.eps)), sdlog = 0.25)\n    )\n  )\n)\n\nbundle_sb_gpd <- build_causal_bundle(\n  y = y,\n  T = T,\n  X = X,\n  kernel = \"laplace\",\n  backend = \"sb\",\n  PS = \"logit\",\n  GPD = TRUE,\n  components = 5,\n  param_specs = param_specs_gpd,\n  mcmc_outcome = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 2),\n  mcmc_ps = list(niter = 2500, nburnin = 500, nchains = 1, thin = 1, seed = 2)\n)\n\nbundle_sb_gpd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDPmixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> laplace </td>\n   <td style=\"text-align:center;\"> laplace </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bundle_sb_gpd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDPmixGPD causal bundle summary\nDPmixGPD causal bundle\nPS model: Bayesian logit (T | X) \n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Field </th>\n   <th style=\"text-align:center;\"> Treated </th>\n   <th style=\"text-align:center;\"> Control </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> Backend </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n   <td style=\"text-align:center;\"> Stick-Breaking Process </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Kernel </td>\n   <td style=\"text-align:center;\"> laplace </td>\n   <td style=\"text-align:center;\"> laplace </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Components </td>\n   <td style=\"text-align:center;\"> 5 </td>\n   <td style=\"text-align:center;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> GPD tail </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n   <td style=\"text-align:center;\"> TRUE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> Epsilon </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n   <td style=\"text-align:center;\"> 0.025 </td>\n  </tr>\n</tbody>\n</table>\nOutcome PS included: TRUE \nn (control) = 232 | n (treated) = 268 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_sb_gpd <- run_mcmc_causal(bundle_sb_gpd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: beta\n===== Samplers =====\nRW sampler (5)\n  - beta[]  (5 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|-------------|-------------|-------------|-------------|\n|-------------------------------------------------------|\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_location, beta_ps_location, beta_tail_scale, scale, tail_shape, threshold, w, z\n===== Samplers =====\nRW sampler (41)\n  - alpha\n  - scale[]  (5 elements)\n  - beta_location[]  (20 elements)\n  - beta_ps_location[]  (5 elements)\n  - threshold\n  - beta_tail_scale[]  (4 elements)\n  - tail_shape\n  - v[]  (4 elements)\ncategorical sampler (232)\n  - z[]  (232 elements)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Monitors =====\nthin = 1: alpha, beta_location, beta_ps_location, beta_tail_scale, scale, tail_shape, threshold, w, z\n===== Samplers =====\nRW sampler (41)\n  - alpha\n  - scale[]  (5 elements)\n  - beta_location[]  (20 elements)\n  - beta_ps_location[]  (5 elements)\n  - threshold\n  - beta_tail_scale[]  (4 elements)\n  - tail_shape\n  - v[]  (4 elements)\ncategorical sampler (268)\n  - z[]  (268 elements)\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_sb_gpd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-- PS fit --\nDPmixGPD PS fit\nmodel: logit \n\n-- Outcome fits --\n[control]\nMixGPD fit | backend: Stick-Breaking Process | kernel: Laplace Distribution | GPD tail: TRUE\nn = 232 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n\n[treated]\nMixGPD fit | backend: Stick-Breaking Process | kernel: Laplace Distribution | GPD tail: TRUE\nn = 268 | components = 5 | epsilon = 0.025\nMCMC: niter=2500, nburnin=500, thin=1, nchains=1 \nFit\nUse summary() for posterior summaries; plot() for diagnostics; predict() for predictions.\n```\n\n\n:::\n\n```{.r .cell-code}\nparams(fit_sb_gpd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPosterior mean parameters (causal)\n\n[treated]\nPosterior mean parameters\n\n$alpha\n[1] \"0.883\"\n\n$w\n[1] \"0.47\"  \"0.315\" \"0.168\"\n\n$beta_location\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> 0.116 </td>\n   <td style=\"text-align:center;\"> -0.609 </td>\n   <td style=\"text-align:center;\"> -0.097 </td>\n   <td style=\"text-align:center;\"> 0.771 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> -0.554 </td>\n   <td style=\"text-align:center;\"> 0.415 </td>\n   <td style=\"text-align:center;\"> 0.039 </td>\n   <td style=\"text-align:center;\"> 0.339 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> -0.014 </td>\n   <td style=\"text-align:center;\"> 0.097 </td>\n   <td style=\"text-align:center;\"> 0.557 </td>\n   <td style=\"text-align:center;\"> 1.684 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> -0.143 </td>\n   <td style=\"text-align:center;\"> 0.175 </td>\n   <td style=\"text-align:center;\"> 0.016 </td>\n   <td style=\"text-align:center;\"> 0.438 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> 0.386 </td>\n   <td style=\"text-align:center;\"> -0.152 </td>\n   <td style=\"text-align:center;\"> -0.159 </td>\n   <td style=\"text-align:center;\"> 0.524 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_location\n[1] \"0.428\"  \"0.583\"  \"1.023\"  \"0.13\"   \"-0.305\"\n\n$scale\n[1] \"1.325\" \"1.338\" \"1.493\"\n\n$beta_tail_scale\n[1] \"0.033\"  \"-0.141\" \"0.161\"  \"-0.048\"\n\n$tail_shape\n[1] \"0.026\"\n\n[control]\nPosterior mean parameters\n\n$alpha\n[1] \"1.12\"\n\n$w\n[1] \"0.56\"  \"0.308\"\n\n$beta_location\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> x1 </th>\n   <th style=\"text-align:center;\"> x2 </th>\n   <th style=\"text-align:center;\"> x3 </th>\n   <th style=\"text-align:center;\"> x4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> comp1 </td>\n   <td style=\"text-align:center;\"> 1.182 </td>\n   <td style=\"text-align:center;\"> 0.759 </td>\n   <td style=\"text-align:center;\"> -0.647 </td>\n   <td style=\"text-align:center;\"> 0.202 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp2 </td>\n   <td style=\"text-align:center;\"> -0.824 </td>\n   <td style=\"text-align:center;\"> 0.043 </td>\n   <td style=\"text-align:center;\"> -0.127 </td>\n   <td style=\"text-align:center;\"> 1.994 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp3 </td>\n   <td style=\"text-align:center;\"> -0.045 </td>\n   <td style=\"text-align:center;\"> -0.438 </td>\n   <td style=\"text-align:center;\"> -0.099 </td>\n   <td style=\"text-align:center;\"> 0.643 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp4 </td>\n   <td style=\"text-align:center;\"> -0.137 </td>\n   <td style=\"text-align:center;\"> -0.145 </td>\n   <td style=\"text-align:center;\"> 0.413 </td>\n   <td style=\"text-align:center;\"> -0.102 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comp5 </td>\n   <td style=\"text-align:center;\"> -0.296 </td>\n   <td style=\"text-align:center;\"> -0.17 </td>\n   <td style=\"text-align:center;\"> -0.588 </td>\n   <td style=\"text-align:center;\"> 0.299 </td>\n  </tr>\n</tbody>\n</table>\n$beta_ps_location\n[1] \"-2.575\" \"0.943\"  \"-0.036\" \"0.15\"   \"-0.275\"\n\n$scale\n[1] \"1.052\" \"1.167\"\n\n$beta_tail_scale\n[1] \"0.306\"  \"0.202\"  \"0.098\"  \"-0.083\"\n\n$tail_shape\n[1] \"-0.037\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (interactive()) plot(fit_sb_gpd, family = c(\"density\", \"geweke\", \"caterpillar\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_mean_gpd <- predict(fit_sb_gpd, x = x_eval, type = \"mean\",\n                         interval = \"credible\", nsim_mean = 100)\nif (interactive()) plot(pred_mean_gpd)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_q_gpd <- predict(fit_sb_gpd, x = x_eval, type = \"quantile\",\n                      p = 0.5, interval = \"credible\")\nif (interactive()) plot(pred_q_gpd)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_d_gpd <- predict(fit_sb_gpd, x = x_eval, y = y_eval,\n                      type = \"density\", interval = \"credible\")\nif (interactive()) plot(pred_d_gpd)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_surv_gpd <- predict(fit_sb_gpd, x = x_eval, y = y_eval,\n                         type = \"survival\", interval = \"credible\")\nif (interactive()) plot(pred_surv_gpd)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_gpd <- ate(fit_sb_gpd, newdata = x_eval,\n               interval = \"credible\", nsim_mean = 100)\nif (interactive()) plot(ate_gpd)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqte_gpd <- qte(fit_sb_gpd, probs = c(0.25, 0.5, 0.75),\n               newdata = x_eval, interval = \"credible\")\nif (interactive()) plot(qte_gpd)\n```\n:::\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}