# tools/update_namespace.R
# ----------------------------
# Generate NAMESPACE file manually since roxygen2::parse_package() fails
# in this environment. Run this script whenever you add new exports or S3 methods.
#
# Usage: Rscript tools/update_namespace.R
#

cat("Generating NAMESPACE file...\n")

files <- list.files("R", pattern = "\\.R$", full.names = TRUE)
exports <- c()
s3methods <- c()
imports <- c()

# Common S3 generics
s3_generics <- c(
  "print", "summary", "plot", "predict", "fitted", "residuals",
  "coef", "vcov", "logLik", "AIC", "BIC", "params"
)

for (f in files) {
  lines <- readLines(f, warn = FALSE)
  for (i in seq_along(lines)) {
    if (grepl("^#' @export$", lines[i])) {
      # Next non-comment line should be the function definition
      for (j in (i + 1):min(i + 5, length(lines))) {
        if (!grepl("^#", lines[j]) && nchar(trimws(lines[j])) > 0) {
          # Extract function name
          m <- regmatches(lines[j], regexec("^([a-zA-Z0-9._]+)\\s*(<-|=)\\s*function", lines[j]))[[1]]
          if (length(m) > 1) {
            fname <- m[2]
            # Check if it's an S3 method
            if (grepl("\\.", fname)) {
              parts <- strsplit(fname, "\\.")[[1]]
              generic <- parts[1]
              if (generic %in% s3_generics) {
                class <- paste(parts[-1], collapse = ".")
                s3methods <- c(s3methods, sprintf("S3method(%s,%s)", generic, class))
              } else {
                exports <- c(exports, sprintf("export(%s)", fname))
              }
            } else {
              exports <- c(exports, sprintf("export(%s)", fname))
            }
          }
          break
        }
      }
    }
  }
}

# Parse globals.R for @import and @importFrom
glob_file <- "R/globals.R"
if (file.exists(glob_file)) {
  glob <- readLines(glob_file, warn = FALSE)
  for (line in glob) {
    if (grepl("@import\\s+", line)) {
      pkgs <- trimws(sub(".*@import\\s+", "", line))
      for (pkg in strsplit(pkgs, "\\s+")[[1]]) {
        if (nchar(pkg) > 0 && !grepl("^@", pkg)) {
          imports <- c(imports, sprintf("import(%s)", pkg))
        }
      }
    }
    if (grepl("@importFrom\\s+", line)) {
      rest <- trimws(sub(".*@importFrom\\s+", "", line))
      parts <- strsplit(rest, "\\s+")[[1]]
      pkg <- parts[1]
      fns <- parts[-1]
      for (fn in fns) {
        imports <- c(imports, sprintf("importFrom(%s,%s)", pkg, fn))
      }
    }
  }
}

# Write NAMESPACE file
ns_content <- c(
  "# Generated by tools/update_namespace.R - do not edit by hand",
  "#",
  "# Run: Rscript tools/update_namespace.R",
  "#",
  "# Note: roxygen2's namespace roclet is disabled in DESCRIPTION because",
  "# parse_package() returns 0 blocks in this environment.",
  "",
  unique(imports),
  "",
  unique(exports),
  "",
  unique(s3methods)
)

writeLines(ns_content, "NAMESPACE")
cat("NAMESPACE generated with:\n")
cat("  Imports:", length(unique(imports)), "\n")
cat("  Exports:", length(unique(exports)), "\n")
cat("  S3methods:", length(unique(s3methods)), "\n")
cat("\nDone!\n")
